name: Qt6 CI

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - .gitignore
      - README.md

  pull_request:
    branches:
      - qt6
    paths-ignore:
      - .gitignore
      - README.md

concurrency:
  # cancel jobs on PRs only
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  QT_VERSION: 6.4.2

jobs:
  build:
    name: Build qcocoa
    runs-on: macos-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: source
          fetch-depth: 0

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Download Qt (desktop)
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: ==3.0.*
          version: ${{ env.QT_VERSION }}
          target: desktop

      - name: Prepare Qt (desktop)
        run: |
          rm $Qt6_DIR/lib/cmake/Qt6Gui/Qt6QCocoaIntegrationPlugin*

      - name: Setup ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Build qcocoa
        run: |
          mkdir build && cd build
          qt-cmake ../source/ \
            -G Ninja \
            -DCMAKE_BUILD_TYPE="RelWithDebInfo" \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14
          ninja
          DESTDIR=../install ninja install

      - name: Create artifacts
        run: |
          pushd install/Users/runner/work/qcocoa
          tar cjvf ../../../../../qcocoa.tar.bz2 Qt
          popd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: qcocoa
          path: qcocoa.tar.bz2

  release:
    name: Release qcocoa
    if: github.ref_type == 'tag'
    runs-on: macos-12
    needs: build
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: qcocoa

    - name: Make tarball
      env:
        TAG_NAME: ${{ github.ref_name }}
      run: |
        mv qcocoa.tar.bz2 qcocoa_${TAG_NAME}.tar.bz2

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: qcocoa_${{ github.ref_name }}.tar.bz2
        allowUpdates: true
        draft: true
